# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('attribute_fr_name', models.CharField(max_length=200)),
                ('attribute_en_name', models.CharField(max_length=200)),
                ('attribute_ru_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('model_fr_name', models.CharField(max_length=200)),
                ('model_en_name', models.CharField(max_length=200)),
                ('model_ru_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('value_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('value_fr_name', models.CharField(max_length=200)),
                ('value_en_name', models.CharField(max_length=200)),
                ('value_ru_name', models.CharField(max_length=200)),
            ],
        ),
    ]
