# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complements', '0004_auto_20180131_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('BDD', 'BDD_RMS'), ('LINK', 'Link file')], default='BDD', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
