# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complements', '0005_auto_20180201_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'документ Excel', 'verbose_name_plural': 'документы Excel'},
        ),
    ]
