# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complements', '0006_auto_20180201_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAdeo',
            fields=[
                ('department_adeo_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('department_adeo_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'отдел Адео',
                'verbose_name_plural': 'отделы Адео',
                'ordering': ['department_adeo_id'],
            },
        ),
        migrations.CreateModel(
            name='ModelGroupAdeo',
            fields=[
                ('model_group_adeo_id', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('model_group_adeo_name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'группа моделей Адео',
                'verbose_name_plural': 'группы моделей Адео',
                'ordering': ['model_group_adeo_id'],
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('sub_department_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('sub_department_name', models.CharField(max_length=60)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complements.Department')),
            ],
            options={
                'verbose_name': 'подотдел Адео',
                'verbose_name_plural': 'потделы Адео',
                'ordering': ['sub_department_id'],
            },
        ),
        migrations.CreateModel(
            name='SubDepartmentAdeo',
            fields=[
                ('sub_department_adeo_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('sub_department_adeo_name', models.CharField(max_length=60)),
                ('department_adeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complements.DepartmentAdeo')),
            ],
            options={
                'verbose_name': 'подотдел Адео',
                'verbose_name_plural': 'потделы Адео',
                'ordering': ['sub_department_adeo_id'],
            },
        ),
        migrations.AddField(
            model_name='modelgroupadeo',
            name='su_department_adeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complements.SubDepartmentAdeo'),
        ),
        migrations.AddField(
            model_name='lmcode',
            name='lmcode_sub_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complements.SubDepartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='model_department_adeo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complements.DepartmentAdeo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='model_group_adeo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complements.ModelGroupAdeo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='model_sub_department_adeo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complements.SubDepartmentAdeo'),
            preserve_default=False,
        ),
    ]
